In [1]:
# ==========================================
# IMPORT LIBRARIES & LOAD DATA
# ==========================================
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, f1_score, confusion_matrix

# Load the dataset (Make sure this path matches your Kaggle setup)
df = pd.read_csv('/kaggle/input/datasets/adeolu20/natural-disaster/natural-disasters.csv')


# ==========================================
# TASK 1: INSPECT THE DATASET
# ==========================================
print("--- TASK 1: DATA INSPECTION ---")
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])
print("Number of missing values:", df.isnull().sum().sum())
print("\n")


# ==========================================
# TASK 2: PREPARE THE DATASET
# ==========================================
# 1. Handle missing values
# Fill numerical missing values with 0
num_cols = df.select_dtypes(include=['float64', 'int64']).columns
df[num_cols] = df[num_cols].fillna(0)

# Fill categorical missing values (if any) with 'Unknown'
cat_cols = df.select_dtypes(include=['object']).columns
df[cat_cols] = df[cat_cols].fillna('Unknown')

# 2. Engineer a Binary Classification Target
# Predicting if a disaster affected > 0 people (1 = Yes, 0 = No)
df['Has_High_Impact'] = (df['Number of total people affected by disasters'] > 0).astype(int)

# Drop columns directly related to our target to avoid data leakage
cols_to_drop = [col for col in df.columns if 'affected' in col.lower() or 'disasters' in col.lower()]
X = df.drop(columns=cols_to_drop + ['Has_High_Impact'])
y = df['Has_High_Impact']

# 3. Encode categorical features (e.g., 'Entity' / Country names)
X = pd.get_dummies(X, columns=cat_cols, drop_first=True)

# 4. Split into Training and Testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


# ==========================================
# TASK 3: BUILD CLASSIFICATION MODELS
# ==========================================
# Initialize models
log_reg = LogisticRegression(max_iter=2000)
dec_tree = DecisionTreeClassifier(random_state=42)
rand_forest = RandomForestClassifier(random_state=42)

# Train the models
log_reg.fit(X_train, y_train)
dec_tree.fit(X_train, y_train)
rand_forest.fit(X_train, y_train)


# ==========================================
# TASK 4: EVALUATE THE MODELS
# ==========================================
print("--- TASK 4: MODEL EVALUATION ---")

def evaluate_and_report(model_name, model, X_test, y_test):
    y_pred = model.predict(X_test)
    print(f"--- {model_name} ---")
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print("Precision:", precision_score(y_test, y_pred, zero_division=0))
    print("F1-score:", f1_score(y_test, y_pred, zero_division=0))
    print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
    print("\n")

# Run evaluations
evaluate_and_report("Logistic Regression", log_reg, X_test, y_test)
evaluate_and_report("Decision Tree", dec_tree, X_test, y_test)
evaluate_and_report("Random Forest", rand_forest, X_test, y_test)

--- TASK 1: DATA INSPECTION ---
Number of rows: 1604
Number of columns: 171
Number of missing values: 34912




/tmp/ipykernel_16/2399660649.py:40: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['Has_High_Impact'] = (df['Number of total people affected by disasters'] > 0).astype(int)
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


--- TASK 4: MODEL EVALUATION ---
--- Logistic Regression ---
Accuracy: 0.8504672897196262
Precision: 0.9736842105263158
F1-score: 0.8851674641148325
Confusion Matrix:
 [[ 88   5]
 [ 43 185]]


--- Decision Tree ---
Accuracy: 0.8722741433021807
Precision: 0.943127962085308
F1-score: 0.9066059225512528
Confusion Matrix:
 [[ 81  12]
 [ 29 199]]


--- Random Forest ---
Accuracy: 0.8940809968847352
Precision: 0.9532710280373832
F1-score: 0.9230769230769231
Confusion Matrix:
 [[ 83  10]
 [ 24 204]]


